### ISSUE TITLE
In mobile device number keypad not showing and alpha character allowing

### ISSUE THREAD

**Issue by dhanarajp** [changhuixu/ngx-digit-only#15]
In Mobile Android OS, chrome and Firefox browser allowing alpha character and instead of number keypad its showing alpha numeric keypad.

example:
"text input with pattern attribute"
 working excepted behavior in ios, but in Android OS chrome and Firefox not working

**Comment by changhuixu** [comment]
Hi @dhanarajp , Could you try to use the examples of "Digt Only input test in mobile device"?
