### ISSUE TITLE
doesn't work on firefox

### ISSUE THREAD

**Issue by eliezer387** [changhuixu/ngx-digit-only#16]
when you try to paste on mozilla firefox does not work

**Comment by eliezer387** [comment]
> when you try to paste on mozilla firefox does not work

I changed document.execCommand(...); for 
this.renderer.setProperty(this.inputElement, 'value', pastedInput); and it worked

**Comment by changhuixu** [comment]
Hi @eliezer387 , you are right. 
I currently don't have a quick solution for this issue. I will research more. 
Thank you.

**Comment by eliezer387** [comment]
I was trying to fix it, I used renderer2 to set the value to the element, visually the value was pasted but the formcontrol didn't get that value, I don't know if I was missing something

**Comment by changhuixu** [comment]
Yes, please try. Thank you.

PS:
set value to input doesn't need renderer2...
We cannot directly set input element value, because if you paste a string in the middle of two digits, simply concatenate the input value would be wrong.

**Comment by FatemeFazli** [comment]
#17

**Comment by changhuixu** [comment]
@FatemeFazli Thank you. I merged it and release v1.2.0
But this pull request doesn't solve all the problems in Firefox...

**Comment by FatemeFazli** [comment]
@changhuixu Thank you, I used it and now copy paste works in Firefox that doesn't supports `insertText` command , Although pastes all characters plus numbers but it's better than before. Thank you;)

**Comment by Cavayman** [comment]
Hmm, also facing this issue do you have some solution? 
On my side changing clipboard text is not working either

**Comment by gabrielhof** [comment]
@changhuixu @Cavayman I think this two lines are not right:
https://github.com/changhuixu/ngx-digit-only/blob/master/projects/uiowa/digit-only/src/lib/digit-only.directive.ts#L82
https://github.com/changhuixu/ngx-digit-only/blob/master/projects/uiowa/digit-only/src/lib/digit-only.directive.ts#L111

They are just setting the pasted/dropped content into the clipboard without filtering the non digits characters. I think it should be doing something like this:

```javascript
navigator.clipboard.writeText(pastedInput.replace(/[^0-9]/g, ''));
```

If you guys don't mind, I can fork the project and open up a PR.

**Comment by changhuixu** [comment]
@gabrielhof Yes, it should be the line in your comment. Please feel free to make PRs.

**Comment by gabrielhof** [comment]
@changhuixu I made some tests using `navigator.clipboard.writeText` and `document.execCommand' but neither of them seem to work on Firefox. The only way I found was to call `setRangeText` in the input element:

```javascript
const {selectionStart: start, selectionEnd: end} = this.inputElement;
this.inputElement.setRangeText(digitsOnlyContent, start, end, 'end');
```

Does that sound an acceptable solution?

**Comment by changhuixu** [comment]
Thank you, @gabrielhof . I used your idea and updated the package. Could you review and test?
If it looks good, then I will release a new version of this npm package.
Thanks.

**Comment by gabrielhof** [comment]
Yeah sure, I'll take a look and test during this weekend.

**Comment by hvn-devrus** [comment]
@changhuixu: Thank you for this very helpful directive. Can you add an addition input to the directive to limit the digit after the decimal point? for example @Input() scale?:number. If the scale is presented, we will limit the number of digit to the right of the decimal point to the value of the scale input, unlimited otherwise. This is helpful in case of the money input value like $20.00.

**Comment by gabrielhof** [comment]
@changhuixu
I just tested and it is looking good. I left a suggestion on the PR in case you want to remove a piece of duplicated code.

@hvn-devrus 
Maybe you could open up another issue with that suggestion, what do you think?

**Comment by changhuixu** [comment]
@gabrielhof Thank you. I have updated the code. The new version is v1.2.2.

@hvn-devrus I think it might be easier to use local logic with form validation...
