### ISSUE TITLE
Add support for decimal places

### ISSUE THREAD

**Issue by swftvsn** [changhuixu/ngx-digit-only#2]
Hi,

We'd like to have support for allowing numbers like '123.45' and to be able to limit the number of decimal places to 2 or let's say 4. 

This in essence requires to know the whole value of the input to do the validation. Do you have any idea what would be the best way to pull that one off?

I can get the value from the native input, but that is lacking the character(s) to be added, and the hard part is to know where the cursor is. (So that we could construct the resulting value of the input if we let the event continue.)

Thank you for the superb library, it is doing exactly what it says! (And we'd like it to do more :))

**Comment by CodeBroJohn** [comment]
I have also been trying to figure out how to make it support decimals. I would like to use this library to help prevent users from anything other than a dollars.cents value in to my input. EX 10.95

**Comment by lakshman53** [comment]
hi,

i have added a PR with the modified changes [here](https://github.com/changhuixu/ngx-digit-only/pull/12/commits/fc42bbecc11343033164760a98e0a9bcf8c34b86).

It will not allow to enter more than one decimal
Will allow to paste or drop content with only one decimal. 

the updated directive code is as follows:

```
import { Directive, ElementRef, HostListener } from '@angular/core';

@Directive({
  selector: '[digitOnly]'
})
export class DigitOnlyDirective {
  private decimalCounter = 0;
  private navigationKeys = [
    'Backspace',
    'Delete',
    'Tab',
    'Escape',
    'Enter',
    'Home',
    'End',
    'ArrowLeft',
    'ArrowRight',
    'Clear',
    'Copy',
    'Paste'
  ];
  inputElement: HTMLElement;
  constructor(public el: ElementRef) {
    this.inputElement = el.nativeElement;
  }

  @HostListener('keydown', ['$event'])
  onKeyDown(e: KeyboardEvent) {

    e.key === '.' ? this.decimalCounter++ : '';

    if (
      this.navigationKeys.indexOf(e.key) > -1 || // Allow: navigation keys: backspace, delete, arrows etc.
      (e.key === 'a' && e.ctrlKey === true) || // Allow: Ctrl+A
      (e.key === 'c' && e.ctrlKey === true) || // Allow: Ctrl+C
      (e.key === 'v' && e.ctrlKey === true) || // Allow: Ctrl+V
      (e.key === 'x' && e.ctrlKey === true) || // Allow: Ctrl+X
      (e.key === 'a' && e.metaKey === true) || // Allow: Cmd+A (Mac)
      (e.key === 'c' && e.metaKey === true) || // Allow: Cmd+C (Mac)
      (e.key === 'v' && e.metaKey === true) || // Allow: Cmd+V (Mac)
      (e.key === 'x' && e.metaKey === true) ||
      (e.key === '.' && this.decimalCounter <= 1)// Allow: Cmd+X (Mac)
    ) {
      // let it happen, don't do anything
      return;
    }
    // Ensure that it is a number and stop the keypress
    if (e.key === ' ' || isNaN(Number(e.key))) {
      e.preventDefault();
    }
  }

  @HostListener('paste', ['$event'])
  onPaste(event: ClipboardEvent) {
    event.preventDefault();
    const pastedInput: string = event.clipboardData
      .getData('text/plain')
      .replace(/[^0-9.]/g, ''); // get a digit-only string

    if (this.hasMoreThanOneDecimal(pastedInput)) {
      document.execCommand('insertText', false, pastedInput);
    }

  }

  @HostListener('drop', ['$event'])
  onDrop(event: DragEvent) {
    event.preventDefault();
    const textData = event.dataTransfer.getData('text').replace(/[^0-9.]/g, '');
    this.inputElement.focus();

    if (this.hasMoreThanOneDecimal(textData)) {
      document.execCommand('insertText', false, textData);
    }

  }

  hasMoreThanOneDecimal(string: String): boolean {
    return string.split('.').length <= 2;
  }
}

```

``

**Comment by swftvsn** [comment]
Awesome! 

It looks really good, it's only missing two things to be perfect I think: the decimal and thousands separators should be configurable.

Maybe we should do separate configuration service? Then the configuration would be global.  Or then @Input with default value '.'?

Anyway, thank you for your contribution @lakshman53

**Comment by swftvsn** [comment]
Also another thing: `decimalCounter` is not updated on paste, drop or backspace if the backspace deletes the decimal character.

**Comment by swftvsn** [comment]
This stackoverflow discussion explains how to get the selected text or the cursor position in that case:
https://stackoverflow.com/questions/17005823/getting-deleted-character-or-text-on-pressing-delete-or-backspace-on-a-textbox

**Comment by changhuixu** [comment]
v1.1.0 is released. Please try it out. Thank you all.

**Comment by swftvsn** [comment]
At the moment this is unusable for as, as the language we use (Finnish) uses comma (,) as decimal separator. For our users dot (.) is only used at the end of sentence and makes no sense in a number. Our number parser also won't accept that.

I'll see if I can make it configurable today and fix the issues listed above.

**Comment by changhuixu** [comment]
@swftvsn Thank you.
