### ISSUE TITLE
Allows more than the maximum allowed characters when pasted from clipboard

### ISSUE THREAD

**Issue by ppm1988** [changhuixu/ngx-digit-only#21]
I tried to copy-paste this **asd1221wq324** value on the input control which should only allow 3 maximum characters but it pasted all the numbers in the text.

**Comment by changhuixu** [comment]
I tried Chrome and Edge, they worked. Firefox allows text longer than maxlength when pasting. I will try to add some logic in code. Thanks for reporting.

**Comment by changhuixu** [comment]
Hi @ppm1988 , I have released a new minor version. Please let me know if you find any problems. Thank you.
