### ISSUE TITLE
Allowing any character after press dead key

### ISSUE THREAD

**Issue by douglasangeli** [changhuixu/ngx-digit-only#28]
Hello, congratulations and thank you for the good work so far. 😉

I found a small bug when typing in a very specific scenario and I would like to share it with you.

### The problem:

When I press any [Dead Key](https://en.wikipedia.org/wiki/Dead_key) like '~', '^' or '´' and then press any other key this value is allowed

### Browser: 

Chrome  80.0.3987.163

### Image:
![image](https://user-images.githubusercontent.com/14776862/79614727-82436400-80d7-11ea-8a7c-3f1debf1925c.png)

**Comment by changhuixu** [comment]
Hi @douglasangeli , thanks for pointing out this issue, and I have learned something new. 
However, I am not sure how to pull out a keyboard to type a dead key, thus hard to investigate... 

I will keep this issue open. I hope some user would create a pull request to resolve this issue.
