### ISSUE TITLE
Error after build the project

### ISSUE THREAD

**Issue by henleywc** [changhuixu/ngx-digit-only#33]
Good Day,

I just install this control and follow the guideline from the documents but after building the project i get the error below. May i know which part i have miss out? Thanks~

ERROR in ../node_modules/@uiowa/digit-only/lib/digit-only.directive.d.ts:23:9 - error TS1086: An accessor cannot be declared in an ambient context.

23     get precision(): number;
           ~~~~~~~~~

**Comment by changhuixu** [comment]
The error is from TypeScript. It is recommended to upgrade TypeScript to latest (`^3.8.3`). 

Could you check which TypeScript version are you using? If you are using VS Code, then the TypeScript version (in use) will show in the bottom status bar (on the right corner).

**Comment by changhuixu** [comment]
@henleywc 
I realized that you might be using Angular 8. I have removed that TypeScript getter.

You can update the package to v1.7.1. The problem should go away once you update it.
Thanks for reporting.
