### ISSUE TITLE
Paste not working in IE or Edge

### ISSUE THREAD

**Issue by sonicsuew** [changhuixu/ngx-digit-only#36]
When I try to Paste in IE I get an error because the clipboardData is not available on the event.

I can also see that the pasteData method uses the HTMLInputElement setRangeText method which is not supported in IE or Edge.

**Comment by sonicsuew** [comment]
Hi, I have had time to play with this a bit more and found a solution which seems to work for Chrome, IE and Edge. I shall share what I have done.

`  @HostListener('paste', ['$event'])
  onPaste(event: any): void {
    let pastedInput: string;
    if (window['clipboardData']) {
      // Browser is IE
      pastedInput = window['clipboardData'].getData('text');
    } else if (event.clipboardData && event.clipboardData.getData) {
      // Other browsers
      pastedInput = event.clipboardData.getData('text/plain');
    }

    this.pasteData(pastedInput);
    event.preventDefault();
  }

  private pasteData(pastedContent: string): void {
    const sanitizedContent = this.sanitizeInput(pastedContent);
    const pasted = document.execCommand('insertText', false, sanitizedContent);
    if (!pasted) {
      if (this.inputElement.setRangeText) {
        const { selectionStart: start, selectionEnd: end } = this.inputElement;
        this.inputElement.setRangeText(sanitizedContent, start, end, 'end');
      } else {
        // Browser does not support setRangeText, e.g. IE
        this.insertAtCursor(this.inputElement, sanitizedContent);
      }
    }
    this.updateDecimalPoint();
  }

  private insertAtCursor(myField: HTMLInputElement, myValue: string): void {
    const startPos = myField.selectionStart;
    const endPos = myField.selectionEnd;

    myField.value = myField.value.substring(0, startPos) + myValue
      + myField.value.substring(endPos, myField.value.length);

    const pos = startPos + myValue.length;
    myField.focus();
    myField.setSelectionRange(pos, pos);

    this.triggerEvent(myField, 'input');
  }

  private triggerEvent(el: HTMLInputElement, type: string): void {
    if ('createEvent' in document) {
      // modern browsers, IE9+
      const e = document.createEvent('HTMLEvents');
      e.initEvent(type, false, true);
      el.dispatchEvent(e);
    }
  }
`

**Comment by changhuixu** [comment]
Thank you, @sonicsuew .
Could you submit a pull request?

**Comment by sonicsuew** [comment]
Hi @changhuixu . I have created a pull request for you called fix-ie-paste

**Comment by changhuixu** [comment]
Thank you @sonicsuew 
I have merged your pull request and the changes are released in v1.8.0
I will also make another release for Angular 10.
