### ISSUE TITLE
angular 10 compatibility

### ISSUE THREAD

**Issue by lilletech** [changhuixu/ngx-digit-only#37]
when trying to update from angular 9 to 10. I've got this error:

Package "@uiowa/digit-only" has an incompatible peer dependency to "tslib" (requires "^1.10.0", would install "2.0.0")

**Comment by changhuixu** [comment]
Hi @lilletech 
Thanks for reporting. I have released v2.0.0. Could you give it a try and let me know if it works for you? Thanks again.

**Comment by lilletech** [comment]
Some other libraries show me also errors, so i cannot test but i don't have errors anymore about digit-only. Thanks ;-)
