### ISSUE TITLE
input type="number" does not work properly

### ISSUE THREAD

**Issue by gethari** [changhuixu/ngx-digit-only#44]
Hi @changhuixu 

First of all thanks for the good work. The lib is pretty good and has a lot of edge case validations.

But why are all the samples using `input type="text"` which technically sounds wrong because we are expecting a number input.

Our input controls needs a `spinner` which can be controlled by arrow keys on the keyboard. But when we add `digitOnly` to the `input type="number"` there are two problems arise

- Arrow keys to control to increase / decrease the values does not work
- Also when i try to manually enter the `max` value it does not allow me to enter.

Please find the reproducible link here for this bug 🐛 - [CodeSandbox](https://codesandbox.io/s/practical-breeze-hsj2q?file=/src/app/app.component.html)

**Comment by changhuixu** [comment]
Hi @gethari , you are right. The `input type="number"` won't work.
This library is intended to be used in `text` input.

**Comment by gethari** [comment]
@changhuixu is there a way to manually add `spinners`  ?

**Comment by changhuixu** [comment]
If you want the browsers' default number spinner, then I am afraid it's not easy with input type="text".

If you want to customize the spinner, then probably you can make your own component, and style the spinner. 
I searched and found some examples in codepen, for example, 
https://codepen.io/riccardoerra/pen/yVMzwg
https://codepen.io/komarovdesign/pen/PPRbgb?css-preprocessor=less

**Comment by sashatrn** [comment]
We faced also the issue and spent a day that it doesn't work correctly with `input type="number"`. It would be nice if you add on README.md this information.
Thank you.

**Comment by changhuixu** [comment]
Thank you @sashatrn 
I will update the readme.
