### ISSUE TITLE
MaskDirective not supporting dynamic pattern attribute binding

### ISSUE THREAD

**Issue by EngFelix** [changhuixu/ngx-digit-only#50]
I am trying to build a component that allows passing in a dynamic pattern string value.

my.component.html:
```
<input [id]="id" 
       type="text"
       ...
       mask
       [pattern]="pattern"
       [placeholder]="placeholder">
```

It works when I use 'pattern="^somePattern$"', but not when using dynamic attribute binding.
This is because the variable 'this.regex' is set in the constructor, where the pattern is still not present.

I think this can be resolved by setting the variable in an appropriate lifecycle hook.

Version: 2.2.2

**Comment by changhuixu** [comment]
merged your pull request. Thank  you.
released v2.2.3
