### ISSUE TITLE
Can't disable paste

### ISSUE THREAD

**Issue by plmpradeep** [changhuixu/ngx-digit-only#56]
I want to disable paste. But using (paste)="false" with digitOnly directive doesn't work.

```
   <input [(ngModel)]="test" placeholder="Enter Value" type="text" digitOnly
                         [pattern]="getInputPattern()" (input)="onInputChange()" (paste)="false">

**Comment by billn6** [comment]
That did not work for me either, nor did onPaste="return false;" nor trying event.preventDefault(); as suggested [here](https://stackoverflow.com/questions/15320069/how-to-prevent-user-pasting-text-in-a-textbox/15320117). 

The following _did_ work.  It allows you to specify allowPaste=false on the input control.

add this

@Input() allowPaste = true;

and then modify the onPaste as follows

@HostListener('paste', ['$event'])
  onPaste(event: any): void {
    if (this.allowPaste === true) { 
      let pastedInput: string = '';
      if ((window as { [key: string]: any })['clipboardData']) {
        // Browser is IE
        pastedInput = (window as { [key: string]: any })['clipboardData'].getData(
          'text'
        );
      } else if (event.clipboardData && event.clipboardData.getData) {
        // Other browsers
        pastedInput = event.clipboardData.getData('text/plain');
      }

      this.pasteData(pastedInput);
      event.preventDefault();
    } else {  // this prevents the paste 
      event.preventDefault();
      event.stopPropagation();
    }
  }

**Comment by changhuixu** [comment]
Hi @billn6 , I think your solution works.

@plmpradeep , what's your opinion on this one (adding a new input field to control the paste handler)?

**Comment by plmpradeep** [comment]
Yup. Suggested changes work fine.

**Comment by patrykdawid** [comment]
@changhuixu Will you throw a small but needed change into the 2.x branch as well?

**Comment by changhuixu** [comment]
Hi @patrykdawid 
A v2.4.0 is released. Thank you.
