### ISSUE TITLE
Pattern not working

### ISSUE THREAD

**Issue by mniak** [changhuixu/ngx-digit-only#7]
The pattern attribute does not work

**Comment by changhuixu** [comment]
Hi @mniak ,
Could you give more context about your question? 
By definition, the pattern attribute specifies a regular expression that the <input> element's value is checked against on form submission.
If you have a `form` element wrap the `input` element, then any invalid input will stop form submission.

**Comment by mniak** [comment]
Wow, I thought it would prevent input. Thanks for the quick response.
