### ISSUE TITLE
Chrome autofill bypasses directive

### ISSUE THREAD

**Issue by dylanfricks** [changhuixu/ngx-digit-only#9]
when I click an input and chrome's autofill dropbox shows up, I can select a text entry and it will fill in inputs with the digit-only directive with those non-digit characters

**Comment by changhuixu** [comment]
@dylanfricks Good point.
You can add `autocomplete="off"` to the `<input>` element

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
